# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Dq0 <- function(n, f1, f2, g1, g2) {
    .Call('_iNEXTPD2_Dq0', PACKAGE = 'iNEXTPD2', n, f1, f2, g1, g2)
}

Dq1_2 <- function(n, g1, A) {
    .Call('_iNEXTPD2_Dq1_2', PACKAGE = 'iNEXTPD2', n, g1, A)
}

Dq2 <- function(tmpaL, n, t_bar) {
    .Call('_iNEXTPD2_Dq2', PACKAGE = 'iNEXTPD2', tmpaL, n, t_bar)
}

Dq_2nd <- function(n, g1, A, q) {
    .Call('_iNEXTPD2_Dq_2nd', PACKAGE = 'iNEXTPD2', n, g1, A, q)
}

Dq <- function(tmpaL, n, qs, g1, A, t_bar) {
    .Call('_iNEXTPD2_Dq', PACKAGE = 'iNEXTPD2', tmpaL, n, qs, g1, A, t_bar)
}

delta <- function(del_tmpaL, k, n) {
    .Call('_iNEXTPD2_delta', PACKAGE = 'iNEXTPD2', del_tmpaL, k, n)
}

delta_part2 <- function(ai, k, n) {
    .Call('_iNEXTPD2_delta_part2', PACKAGE = 'iNEXTPD2', ai, k, n)
}

RPD_old <- function(x, n, m, q) {
    .Call('_iNEXTPD2_RPD_old', PACKAGE = 'iNEXTPD2', x, n, m, q)
}

RPD <- function(ai, Lis, n, m, q) {
    .Call('_iNEXTPD2_RPD', PACKAGE = 'iNEXTPD2', ai, Lis, n, m, q)
}

ghat_pt2 <- function(ai, n, mmax) {
    .Call('_iNEXTPD2_ghat_pt2', PACKAGE = 'iNEXTPD2', ai, n, mmax)
}

qD_MLE <- function(q, ai) {
    .Call('_iNEXTPD2_qD_MLE', PACKAGE = 'iNEXTPD2', q, ai)
}

